repos:
  -  repo: https://github.com/asottile/pyupgrade
     rev: v2.37.1
     hooks:
     -   id: pyupgrade
         language_version: python3.8

  - repo: https://github.com/adamchainz/django-upgrade
    rev: '1.7.0'
    hooks:
      - id: django-upgrade
        args: [ --target-version, "3.1" ]

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/python/black
    rev: '22.6.0'
    hooks:
      - id: black
        exclude: ^.*\b(migrations)\b.*$
        language_version: python3.8
        args: [
            --skip-string-normalization,
            -l 120,
        ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: detect-private-key
      - id: check-executables-have-shebangs
      - id: check-case-conflict
      - id: trailing-whitespace
      - id: check-symlinks
      - id: flake8

  - repo: https://github.com/PyCQA/pylint
    rev: v2.14.5
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        exclude: ^.*\b(migrations)\b.*$
        types: [ python ]
        args:
          - --errors-only
          - --rcfile=.pylintrc
          - --load-plugins=pylint_django
